name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install cabal-install & ghc
      run: |
        sudo add-apt-repository ppa:hvr/ghc
        sudo apt-get update
        sudo apt-get install ghc-8.6.5 cabal-install-2.4
        export PATH="/opt/ghc/bin:$PATH"
        cabal --version
        ghc --version
    - name: Install dependencies
      run: cabal v2-install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal v2-configure --enable-tests
        cabal v2-build
    - name: Run tests
      run: cabal v2-test
